FROM rust:1.72-slim-bullseye

WORKDIR /usr/src/app
RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    build-essential \
    cmake \
    libclang-dev \
    libzstd-dev \
    clang \
    gcc \
    g++ \
    git \
    make

COPY . .

ENV ZSTD_SYS_USE_PKG_CONFIG=1
ENV RUSTFLAGS="-C target-feature=-crt-static"

RUN cargo build --release

CMD ["cp", "target/release/https-web-server-example", "/output/"]